# workflow to publish the cli project on npm

name: cli

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'packages/cli/**'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: git config --global user.email "test@example.com"
      - run: git config --global user.name "Alexander Bartels"
      - run: npm ci
      - run: npm run build --workspaces --if-present
      - run: npm run release -w packages/cli
      - name: publish tag
        id: publish_tag
        run: |
          git push --follow-tags origin main
          echo ::set-output name=tag_name::$(git describe HEAD --abbrev=0)
      - run: npx extract-changelog-release packages/cli/CHANGELOG.md > CLI_RELEASE_BODY.md
      - run: echo ${{ steps.publish_tag.outputs.tag_name }}
      - name: create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ steps.publish_tag.outputs.tag_name }}
          tag_name: ${{ steps.publish_tag.outputs.tag_name }}
          body_path: CLI_RELEASE_BODY.md
      - run: npm publish -w packages/cli --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
